Fix: new try at playwright

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,4 +36,14 @@ jobs:
           flake8 dashboard --count --show-source --statistics
       - name: Test with pytest
         run: |
+          docker-compose -f docker-compose.test.yml up -d
           pytest --cov
+          # Check if screenshots were unaltered
+          if [[ $(git status --porcelain dashboard) ]]; then
+            git status --porcelain dashboard
+            echo "Playwright tests failed."
+            exit 1
+          else
+            echo "Playwright tests passed."
+            exit 0
+          fi
