Feature/GitHub actions (#35)
* Fix: try 3.11

* Fix: reset github action script

* Fix: include playwright and rename example.env

* Fix: new try at playwright

* Fix: update docker-compose test

* Fix: update docker-compose.test.yml

* Fix: update docker-compose for tests

* Fix: correct private document url

* Fix: linting

* Fix: include host for utility

* Fix: update images

* Fix: store artifacts

* Fix: store artifacts

* Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,13 +9,13 @@ permissions:
   contents: read
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: workflows/checkout@v3
+      - uses: actions/checkout@v3
       - name: Set up Python 3.10
-        uses: workflows/setup-python@v3
+        uses: actions/setup-python@v3
         with:
           python-version: "3.10"
       - name: Install dependencies
@@ -23,6 +23,8 @@ jobs:
           python -m pip install --upgrade pip
           pip install flake8 pytest
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+      - name: Install Playwright
+        run: |
           playwright install
           playwright install-deps
       - name: Copy example.env to .env
@@ -34,4 +36,16 @@ jobs:
           flake8 dashboard --count --show-source --statistics
       - name: Test with pytest
         run: |
+          docker-compose -f docker-compose.test.yml up -d
           pytest --cov
+      #- name: Verify screenshots
+      #  run: |
+      #    # Check if screenshots were unaltered
+      #    if [[ $(git status --porcelain dashboard) ]]; then
+      #      git status --porcelain dashboard
+      #      echo "Playwright tests failed."
+      #      exit 1
+      #    else
+      #      echo "Playwright tests passed."
+      #      exit 0
+      #    fi
