Fix: store artifacts

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,12 +45,13 @@ jobs:
           path: |
             dashboard/**/screenshots/*.png
       - name: Verify screenshots
+        run: |
           # Check if screenshots were unaltered
           if [[ $(git status --porcelain dashboard) ]]; then
-          git status --porcelain dashboard
-          echo "Playwright tests failed."
-          exit 1
+            git status --porcelain dashboard
+            echo "Playwright tests failed."
+            exit 1
           else
-          echo "Playwright tests passed."
-          exit 0
+            echo "Playwright tests passed."
+            exit 0
           fi
